version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands: 
      - echo Installing source NPM dependencies...
      - cd OJT-app
      - npm i -g @angular/cli
      - npm install
      - npm i @angular-devkit/build-angular --dev
  build:
    commands:
      - echo Build started on `date`
      - ng build
  post_build:
     commands:
      - echo Build completed on `date`
artifacts:
  files:
      - OJT-app/dist/**/*
      - OJT-app/appspec.yml
      - OJT-app/scripts/*.sh