version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  post_build:
    commands:
    - echo building the spring-boot
    - mvn package
artifacts:
  files:
  - target/*.jar
  - prod/*.sh
  - prod/appspec.yml
  discard-paths: yes

cache:
  paths:
  - '/root/.m2/**/*'